function ResultCard({ result }) {
  if (!result) return null;

  const moonSign = result?.response?.moon_sign || "Unknown";
  const aiSummary =
    result?.response?.bot_response || "No AI summary available.";
  const prediction =
    result?.response?.prediction || "No prediction available.";

  return (
    <div className="mt-10">

      <div className="rounded-3xl border border-white/10 bg-white/10 backdrop-blur-xl shadow-2xl overflow-hidden">

        {/* Header */}
        <div className="bg-gradient-to-r from-purple-700 via-indigo-700 to-blue-700 p-8 text-center">

          <div className="text-6xl mb-4">🌙</div>

          <h2 className="text-4xl font-bold text-white">
            {moonSign}
          </h2>

          <p className="text-purple-100 mt-2 text-lg">
            Your Cosmic Moon Sign
          </p>

        </div>

        {/* Content */}
        <div className="p-8 space-y-6">

          {/* AI Summary */}
          <div className="rounded-2xl bg-purple-900/30 border border-purple-500/20 p-6">

            <h3 className="text-2xl font-semibold text-purple-300 mb-4">
              🤖 AI Summary
            </h3>

            <p className="text-gray-200 leading-8">
              {aiSummary}
            </p>

          </div>

          {/* Prediction */}
          <div className="rounded-2xl bg-indigo-900/30 border border-indigo-500/20 p-6">

            <h3 className="text-2xl font-semibold text-indigo-300 mb-4">
              📖 Prediction
            </h3>

            <p className="text-gray-200 leading-8">
              {prediction}
            </p>

          </div>

          {/* Quick Insights */}
          <div className="grid md:grid-cols-3 gap-5">

            <div className="rounded-2xl bg-white/5 border border-white/10 p-5 text-center">
              <div className="text-3xl mb-2">💼</div>

              <h4 className="font-semibold text-cyan-300">
                Career
              </h4>

              <p className="text-gray-400 text-sm mt-2">
                AI-based career guidance will appear here in future updates.
              </p>
            </div>

            <div className="rounded-2xl bg-white/5 border border-white/10 p-5 text-center">
              <div className="text-3xl mb-2">❤️</div>

              <h4 className="font-semibold text-pink-300">
                Relationships
              </h4>

              <p className="text-gray-400 text-sm mt-2">
                Relationship compatibility insights will be available here.
              </p>
            </div>

            <div className="rounded-2xl bg-white/5 border border-white/10 p-5 text-center">
              <div className="text-3xl mb-2">⭐</div>

              <h4 className="font-semibold text-yellow-300">
                Personality
              </h4>

              <p className="text-gray-400 text-sm mt-2">
                Your strengths and personality traits will be expanded here.
              </p>
            </div>

          </div>

          {/* Footer */}
          <div className="border-t border-white/10 pt-6 text-center">

            <p className="text-gray-400">
              Generated by <span className="font-semibold text-purple-400">AstroAI</span>
            </p>

          </div>

        </div>

      </div>

    </div>
  );
}

export default ResultCard;